# Generated by Django 4.1.7 on 2023-04-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'SalesRep'), (3, 'OpsManager'), (4, 'Contractor'), (5, 'Customer'), (6, 'ConstructionManager'), (7, 'SiteSurveyor')], default=5),
        ),
    ]
